### ISSUE TITLE
View to manage tenant to understand how to use the session and usercontext

### ISSUE THREAD

**Issue by mach37** [d-saravanan/multitenant.dev.template#1]
Hi, this is nice sample, can you add some code like a view to manage the tenants.

to help us understand 

- how to save data to the correct tenant when a page is saved
- get the user session context
- add roles and users by session.

thanks

**Comment by d-saravanan** [comment]
Sure, I will work on that. It will take some time as I am not working in this in full-time. Kindly bear :)

**Comment by mach37** [comment]
sure 👍

**Comment by winecraft** [comment]
I am also looking forward to this, ASP MVC 5 identity 2.2 correct.

**Comment by d-saravanan** [comment]
I have updated the documentation detailing the usage, and explaining the tenant context and service templates. In case of any questions, let me know. The documentation is available [here](https://d-saravanan.github.io/multitenant.dev.template/). You may reach me via my email id given in in the documentation page or leave me a message here.

**Comment by winecraft** [comment]
Can you also release ASP MVC 5 version like I requested couple days ago.

How is IRepository service different from the DBContext, that we get when the controllers are scaffolded?

**Comment by mach37** [comment]
if you're not going to update I will close this out!

**Comment by d-saravanan** [comment]
@winecraft : The IRepository is very helpful in the process of unit testing and helps you to mock the DbContext and hence it is highly testable and you can switch from EF to any other ORM or to SQLClient if required. This results in clean code, separation of concerns and ease of use. Hope this clarifies your question

**Comment by d-saravanan** [comment]
@winecraft , @mach37 : I have added a new enhancement ticket for the MVC part. As mentioned earlier, I am not working in this full time and will require sometime for me to implement. Kindly review the new enhancement request for updates
